### ISSUE TITLE
Error on :colorscheme highlite

### ISSUE THREAD

**Issue by oponkork** [Iron-E/nvim-highlite#1]
I added it to neovim via vim-plug and then simply tried setting the colorscheme with `:colorscheme highlite` and it fails with the following error.

```
Error detected while processing /home/oponkork/.local/share/nvim/plugged/nvim-highlite/colors/highlite.vim:
line  741:
E5105: Error while calling lua chunk: [string "<VimL compiled string>"]:52: attempt to index field 'g' (a nil value)
```

**Comment by Iron-E** [comment]
Sorry I missed this! I was away for a month on sabbatical. What version of Neovim are you running? This kind of error would be expected if Neovim is below 0.5

**Comment by oponkork** [comment]
@Iron-E 
Sorry, I realized that the error was because I was using `neovim 0.4`, I tried it with `neovim 0.5` and it is working. I forgot to update here. I will close the issue now.

Thanks for the plugin, I am already using it to set my own colorscheme.

**Comment by Iron-E** [comment]
Glad to hear it!
