### ISSUE TITLE
No more vim

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [Iron-E/nvim-highlite#12]
[14686](https://github.com/neovim/neovim/pull/14686) added Lua support for runtime files. `colors/highlite.vim` can be changed to `colors/highlite.lua`

**Comment by Iron-E** [comment]
I've set up a branch to implement this feature. I couldn't get it to work at first but figured it out eventually.

I'll probably wait a few days to let people update, and then push it.

**Comment by Iron-E** [comment]
The branch was been merged. I think three days is probably good enough ;)

Thanks for letting me know about this! I think some of my other plugins can probably benefit from this too.

**Comment by Th3Whit3Wolf** [comment]
Nicely done! No problem, I think a lot of us are going to need to update our plugins
