### ISSUE TITLE
Possible use of nvim_set_hl

### ISSUE THREAD

**Issue by SanchayanMaity** [Iron-E/nvim-highlite#18]
With https://github.com/neovim/neovim/pull/17187 in place, may be `nvim_set_hl` can be used. Though yes, this is not in released neovim yet.

**Comment by Iron-E** [comment]
There's a new branch called `perf/api-highlights`. In my experience `nvim_set_hl` exhibits strange behavior though, so I may not merge it unless it can actually produce the same results as the `:highlight` method after 0.7 is released.

**Comment by SanchayanMaity** [comment]
@Iron-E Thank you. Makes sense. I will try the `perf/api-highlights` branch locally.

**Comment by zbirenbaum** [comment]
> There's a new branch called `perf/api-highlights`. In my experience `nvim_set_hl` exhibits strange behavior though, so I may not merge it unless it can actually produce the same results as the `:highlight` method after 0.7 is released.
> 
> For example, both `Visual` and `ErrorMsg` are not the right color when using `nvim_set_hl` but are correct when using `:highlight`.

I had this experience when converting base16 to use the lua highlight api, but just for normal mode. To my understanding, if a highlight already exists, for say, fg, and you do nvim_set_hightlight, but only pass in bg, it will replace the fg. 

You can work around this by checking the current highlights and explicitly passing them in, but really that something which should be implemented upstream.

**Comment by Iron-E** [comment]
Closing this issue as `nvim_set_hl` is now used for v2.0.0+ of this plugin. Thank you to @zbirenbaum for helping me debug, and @SanchayanMaity for the suggestion!
