### ISSUE TITLE
Not to sound lazy, but... Recommend a tool to convert all three color codes?

### ISSUE THREAD

**Issue by anoduck** [Iron-E/nvim-highlite#20]
Not to sound horrendously lazy, but I was wondering if you could recommend a tool or web app that would allow free conversion of color codes through the three different required formats. This would be a huge help to ensure precise translation of the different formats to the correct code.

**Comment by Iron-E** [comment]
There is a recommendation for 16-bit [in the walkthrough](https://github.com/Iron-E/nvim-highlite/blob/master/colors/highlite.lua#L78).

Figuring out the ANSI color codes should be pretty easy, since they are literals like 'gray', 'blue', etc.

**Comment by anoduck** [comment]
That one works pretty well, I also found mplcolors as well.

https://github.com/AstroBarker/mplcolors

And although not necessarily useful as a resolution, I found this site to be most informative.

https://easyrgb.com/en/convert.php

**Comment by anoduck** [comment]
That script worked pretty well, especially when combined with a little bash scripting. Here is a list of all 256 different ANSI color names, and just for reference it was more difficult to locate than one would think. 

https://www.ditig.com/256-colors-cheat-sheet

There is a script that helps in locating colors that are complementary:

https://github.com/AstroBarker/mplcolors

And although not particularly applicable here, I found this website informative:

https://easyrgb.com/en/convert.php#inputFORM

**Comment by anoduck** [comment]
@Iron-E to be honest, I feel like a heel. I just got to the latter portion of the colors template, and you provide a whole truck load of information to help perform exactly what I was inquiring about. More than enough to successfully design your own color scheme.  This is going to be a lot of fun, and a proverbial cakewalk.

Tropical Neon, a theme inspired by Miami Vice, is coming to life.
