### ISSUE TITLE
Neovim version requirement in README not matching doc

### ISSUE THREAD

**Issue by sansugranes** [Iron-E/nvim-highlite#22]
The neovim version requirement specified in the [README](https://github.com/Iron-E/nvim-highlite/blob/master-v3/README.md) is different from the version specified in the [highlite.txt](https://github.com/Iron-E/nvim-highlite/blob/master-v3/doc/highlite.txt) doc.

**Comment by Iron-E** [comment]
The one in the highlite.txt file is correct.
