### ISSUE TITLE
bat does not aссept exported theme

### ISSUE THREAD

**Issue by damanis** [Iron-E/nvim-highlite#31]
Export theme to `bat` format (`thTheme`): `lua require('highlite.export').bat(<theme_name>)`
`bat cache -b` returns error with `(reason: 'Invalid syntax theme settings')`

`nvim` version: v0.10.0-dev-2098+g92672a161
`nvim-highlite` version: 4.14.0

**Comment by Iron-E** [comment]
I can confirm. It seems there was a regression with the `tmTheme` specifically.

**Comment by Iron-E** [comment]
Thank you for the report!

**Comment by damanis** [comment]
Thank for fix.
