### ISSUE TITLE
Export to wezterm does not work

### ISSUE THREAD

**Issue by damanis** [Iron-E/nvim-highlite#32]
The call `lua require('highlite.export').wezterm('everforest')` causes error.
Export to `bat`, for example, works properly.

**Comment by Iron-E** [comment]
Thank you for the report! I'll take a look at this tomorrow.

**Comment by Iron-E** [comment]
Odd, it seems my version of Neovim doesn't even have `everforest`. If I change it to `default`, though, it seems to work for me

**Comment by damanis** [comment]
[Everforest for neovim](https://github.com/neanias/everforest-nvim)
But same problem with other themes, for example, [Nightfox](https://github.com/EdenEast/nightfox.nvim).
Same themes are exported to `bat` by `nvim-highlite` without problem.
The error:
![image](https://github.com/user-attachments/assets/f99fa1f0-2e3e-4ee1-86b5-bcf206c4f5d4)

**Comment by Iron-E** [comment]
Thank you for the links, I'll check this out further

**Comment by Iron-E** [comment]
I wasn't able to reproduce with `everforest`; could you share your Neovim version and/or config?

**Comment by damanis** [comment]
I tested both on neovim 0.10.0 and nightly build.
Configuration in lazy:
```
  {'Iron-E/nvim-highlite',
    enabled = true,
    lazy = true,
    priority = math.huge,
    -- version = '^4.0.0',
    config = function(_, opts)
      -- OPTIONAL: setup the plugin. See "Configuration" for information
      require('highlite').setup {generator = {plugins = {vim = false}, syntax = false}}
    end,
  },
```
In `lazy-lock.json`:
```
"nvim-highlite": { "branch": "master-v4", "commit": "83a6fcc41eb55db93eee37199600b547638d3a28" },
```

**Comment by Iron-E** [comment]
I couldn't reproduce the issue, but I do think that I know what the problem is. Could you try #33 to see if the error goes away?

**Comment by damanis** [comment]
@Iron-E 
Yes, with `dir` argument export to wezterm works.
Note. Export to `vim`, for example, does not require `dir` argument, `nvim-highlite` creates output folder itself.
