### ISSUE TITLE
pallete.comment is unused

### ISSUE THREAD

**Issue by wbourne0** [Iron-E/nvim-highlite#35]
Looks like `pallette.comment` isn't used anywhere (instead `text_contrast_bg_low` [is used for comment highlights](https://github.com/Iron-E/nvim-highlite/blob/31f52d52a618aa16d2576da85992ee9b2d10babb/lua/highlite/groups/default.lua#L88)).

`pallette.comment` is documented [here](https://github.com/Iron-E/nvim-highlite/blob/31f52d52a618aa16d2576da85992ee9b2d10babb/doc/advanced-usage.md?plain=1#L186).

**Comment by wbourne0** [comment]
looks like `keyword_exception` is also unused - `throw` is [used instead](https://github.com/Iron-E/nvim-highlite/blob/31f52d52a618aa16d2576da85992ee9b2d10babb/lua/highlite/groups/default.lua#L310).

**Comment by Iron-E** [comment]
Thank you for the report!

I was able to fix the `palette.comment` problem in #36, though I couldn't find a reference for `keyword_exception` being a palette group:

![cap](https://github.com/user-attachments/assets/646bd676-2083-4d51-917b-a2c2d540be47)

Was `keyword_exception` seen in documentation on this repo?

**Comment by wbourne0** [comment]
oops!  Look like I made a mistake. I thought I saw it but i guess not.
