### ISSUE TITLE
Question changing highlights

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [Iron-E/nvim-highlite#9]
Sorry to bug you, I have an [issue where the user can not change the highlight in one-nvim](https://github.com/Th3Whit3Wolf/one-nvim/issues/2)  but can in onebuddy.  

I was able to change highlights by either
- setting an autocmd for it

or

- adding a highlight in `nvim/after/colors/one-nvim.vim` and adding it to the runtime. 

The user was unable to change the highlighting using either of these methods. Do you know if there are anything that colorbuddy does that would allow this where nvim-highlite may not? I am pretty puzzled why this won't work.

**Comment by Iron-E** [comment]
I'll take a look and see what the issue might be. Currently I know that after Neovim loads I can run `hi!` and either link or override what was set by `nvim-highlite`. I'll try embedding the command into a minimal RC so I can replicate the issue.

**Comment by Iron-E** [comment]
I can get the bug to happen with this minimal config:

```vim
packadd nvim-highlite
set termguicolors
colorscheme highlite

hi! Error guifg=#000000 guibg=#FFFFFF
```

I'll keep investigating.

**Comment by Th3Whit3Wolf** [comment]
I think mentioning how to do it on the README or in a wiki  would be fine. It puts whatever the cost of the function is onto the minority of the people that want it.

**Comment by Iron-E** [comment]
Does the referencing commit add instructions which seem clear enough?

**Comment by Th3Whit3Wolf** [comment]
Yeah I think so

**Comment by Th3Whit3Wolf** [comment]
In the future I see lua being more commonplace in neovim configs and with people using `init.lua`s more I am curious how you would write this in lua. I found two ways.

**The ugly way**

```lua
vim.api.nvim_command("augroup Highlight")
vim.api.nvim_command("autocmd!")
vim.api.nvim_command("autocmd ColorScheme highlite hi! Normal guifg=#000000 guibg=#FFFFFF")
vim.api.nvim_command("augroup end")
vim.api.nvim_command("colorscheme highlite")
```

**The prettier way**

```lua
local vim, api, cmd = vim, vim.api, vim.cmd

local function augroups(definitions)
    for group_name, definition in pairs(definitions) do
        api.nvim_command("augroup " .. group_name)
        api.nvim_command("autocmd!")
        for _, def in ipairs(definition) do
            local command = table.concat(vim.tbl_flatten {"autocmd", def}, " ")
            api.nvim_command(command)
        end
        api.nvim_command("augroup END")
    end
end

local autocmds = {
    Highlight = {
        {"ColorScheme", "highlite", "hi! Normal guifg=#000000 guibg=#FFFFFF"}
    }
}

augroups(autocmds)
cmd 'colorscheme highlite'
```

The second way also blends in more with the config if you use the `augroups` function for generating all of your autocmds.

I'm not very experienced with lua thought so I'm curious if you have a nice way of doing it.

**Comment by Iron-E** [comment]
I definitely see Lua being the way to go in the future too. If you use multiline strings for the `nvim_command` it's a little prettier:

```lua
vim.api.nvim_command[[
    augroup Highlight
        autocmd!
        autocmd ColorScheme highlite hi! Normal guifg=#000000 guibg=#FFFFFF
    augroup end
    colorscheme highlite
]]
```

I believe the Neovim team is working on a wrapper for autocommands in Lua. After that is complete you'll be able to do this even more easily (although we don't know what it looks like yet).
